version: 1.0.{build}
image: Visual Studio 2017

only_commits:
  message: test
 
configuration:
- Release

before_build:

build:
  project: NuttyPutters.sln
  parallel: true
  verbosity: minimal
  
artifacts:
- path: x64/Release$(configuration)/NuttyPutters.exe